FROM thanhphu/dbbench-src

RUN sed --in-place --regexp-extended "s/(\/\/)(kr\.archive\.ubuntu\.com)/\1ftp\.harukasan\.org/" /etc/apt/sources.list && \
	apt-get update && apt-get upgrade --yes

RUN apt install libhiredis-dev

USER ${RUN_USER}
COPY entrypoint.sh /
USER root
CMD ["/entrypoint.sh", "-fg"]
ENTRYPOINT ["/bin/bash", "--"]

EXPOSE 22
