FROM thanhphu/dbbench-srchttps://kudaha.atlassian.net/wiki/spaces/BlockchainResearch/pages/318537868/Lab+StateDB

USER ${RUN_USER}
COPY entrypoint.sh /
USER root
CMD ["/entrypoint.sh", "-fg"]
ENTRYPOINT ["/bin/bash", "--"]

EXPOSE 22
