FROM thanhphu/dbbench-base

WORKDIR /src
## build boost 1.65.0
RUN wget http://dl.bintray.com/boostorg/release/1.65.0/source/boost_1_65_0.tar.gz \
    && tar xzvf boost_1_65_0.tar.gz \
    && cd boost_1_65_0 \
    && ./bootstrap.sh --prefix=/usr/ \
    && ./b2 --with-system --with-program_options \
    && ./b2 install

WORKDIR /src
## build gflags
RUN wget https://github.com/gflags/gflags/archive/v2.2.2.tar.gz \
    && tar xzf v2.2.2.tar.gz \
    && cd gflags-2.2.2 && mkdir build && cd build \
    && cmake .. -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=ON -DBUILD_gflags_LIB=ON \
    && make -j \
    && make install

WORKDIR /src
## build gtest
RUN git clone -b release-1.8.1 https://github.com/google/googletest \
    && cd googletest && mkdir build && cd build \
    && cmake -DCMAKE_BUILD_TYPE=Release .. \
    && make -j \
    && make install

WORKDIR /src
## build glog
RUN git clone https://github.com/google/glog.git \
    && cd glog \
    && cmake -DCMAKE_BUILD_TYPE=Release -H. -Bbuild -G "Unix Makefiles" \
    && cmake --build build -- -j \
    && cmake --build build --target install

WORKDIR /src
RUN git clone -b 1.22 https://github.com/google/leveldb \
    && cd leveldb \
    && mkdir -p build && cd build \
    && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . -- -j \
    && make install

WORKDIR /src
RUN git clone -b v6.4.6 https://github.com/facebook/rocksdb \
    && cd rocksdb \
    && EXTRA_LDFLAGS="-ldl" make shared_lib \
    && make install

ENV REDIS_VERSION=4.0.9 \
    REDIS_USER=redis \
    REDIS_DATA_DIR=/var/lib/redis \
    REDIS_LOG_DIR=/var/log/redis

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y apt-utils redis-server=5:${REDIS_VERSION}* \
 && rm /etc/redis/redis.conf

# RUN echo 1024 > /proc/sys/net/core/somaxconn
# RUN echo never > /sys/kernel/mm/transparent_hugepage/enabled

EXPOSE 6379/tcp

ENV ROOT_HOME /root
ENV SPEEDUS_DIR /opt/torusware/speedus
ENV NETPIPE_DIR $SPEEDUS_DIR/benchmarks/NetPIPE-C

RUN apt-get -qqy install wget unzip make gcc

RUN mkdir -p /opt/torusware \
 && cd /opt/torusware \
 && wget http://dl.torusware.com/speedus/release/speedus-latest-linux.zip \
 && unzip speedus-latest-linux.zip \
 && rm speedus-latest-linux.zip \
 && ln -s speedus-b* $SPEEDUS_DIR \
 && cp $SPEEDUS_DIR/doc/README.image.txt $ROOT_HOME/SPEEDUS_README.txt

RUN cd $NETPIPE_DIR \
 && make \
 && cp NPtcp /usr/bin/NPtcp

COPY speedus /usr/local/bin/speedus

RUN apt-get -y install libhiredis-dev

WORKDIR /src
RUN git clone https://github.com/sewenew/redis-plus-plus.git \
    && cd redis-plus-plus \
    && mkdir compile \
    && cd compile \
    && cmake -DCMAKE_BUILD_TYPE=Release .. \
    && make \
    && make install



