FROM ubuntu:18.04 AS base

ENV LD_LIBRARY_PATH /usr/local/lib

RUN sed --in-place --regexp-extended "s/(\/\/)(archive\.ubuntu)/\1kr.\2/" /etc/apt/sources.list && \
	apt-get update && apt-get upgrade --yes

RUN apt-get update \
    && apt-get install -y \
    build-essential \
    cmake=3.10.2-1ubuntu2.18.04.1 \
    git \
    g++ \
    libevent-dev=2.1.8-stable-4build1 \
    libpthread-stubs0-dev=0.3-4 \
    libsecp256k1-dev=0.1~20170810-1 \
    libssl-dev=1.1.1-1ubuntu2.1~18.04.4 \
    python3

RUN apt-get install -y \
    autoconf \
    automake \
    clang-5.0=1:5.0.1-4 \
    libc++-dev=6.0-2 \
    libtool \
    libxml2-dev \
    libxslt-dev \
    pkg-config \
    python-dev \
    wget

ENV RUN_USER medium
ENV RUN_GROUP medium
ENV USER_PASSWORD medium@1234
ENV DEBIAN_FRONTEND noninteractive
RUN useradd -ms /bin/bash ${RUN_USER}

RUN apt-get -y install \
    gdb=8.1-0ubuntu3 \
    gdbserver=8.1-0ubuntu3 \
    openssh-server \
    rsync=3.1.2-2.1ubuntu1
